# Generated by Django 3.1.7 on 2021-03-23 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("card", "0001_initial"),
        ("tournament", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeamPlayerCard",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "player_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="card.playercard",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="player_cards",
                        to="tournament.team",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="teamplayercard",
            constraint=models.UniqueConstraint(
                fields=("team", "player_card"), name="unicity_of_player_card_in_team"
            ),
        ),
    ]
