# Generated by Django 3.1.7 on 2021-03-23 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0002_auto_20210323_1553"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="league",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tournament.league",
            ),
        ),
        migrations.AddConstraint(
            model_name="team",
            constraint=models.UniqueConstraint(
                fields=("user", "league"), name="a_user_can_have_one_team_per_league"
            ),
        ),
    ]
