# Generated by Django 3.1.7 on 2021-03-23 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("card", "0001_initial"),
        ("tournament", "0003_auto_20210323_1615"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="player_cards",
            field=models.ManyToManyField(
                through="tournament.TeamPlayerCard", to="card.PlayerCard"
            ),
        ),
        migrations.AlterField(
            model_name="teamplayercard",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tournament.team"
            ),
        ),
        migrations.CreateModel(
            name="TournamentPlayerCard",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "player_card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="card.playercard",
                    ),
                ),
                (
                    "tournament",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tournament.tournament",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="tournamentplayercard",
            constraint=models.UniqueConstraint(
                fields=("tournament", "player_card"),
                name="unicity_of_player_card_in_tournament",
            ),
        ),
    ]
