# Generated by Django 3.1.7 on 2021-03-23 22:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("tournament", "0004_auto_20210323_2131"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="creation_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="team",
            name="score",
            field=models.FloatField(db_index=True, default=0.0),
        ),
    ]
