# Generated by Django 3.1.7 on 2021-03-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playercard',
            name='bonus',
            field=models.FloatField(default=1.0),
        ),
    ]
